name: blow.com
favicon: null
layout_spectrum: 0.2558554436545819
typography_spectrum: 0.9317701756954193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7517836512997746
  lightness: 0.669789589708671
  saturation: 0.42219008365646005
  rhythmicContrast: 0.09284958383068442
purpose: []
